"""
One-time PII scrub of the live database (HOSTING_PLAN.md Track B.1).

Makes email senders/recipients untraceable:
  1. Nulls emails.email_from / email_to.
  2. Scrubs free text (forwarded-header lines + email addresses) in:
       emails.email_subject, emails.email_body
       email_chunks.email_subject, email_chunks.chunk_text
       key_points_full.email_subject, key_point_text/citation/context
       trade_ideas_full.email_subject, trade_idea_text/citation/context
  3. Recomputes email_body_length and refreshes kp_fts / ti_fts for changed rows.
  4. Truncates chat_traces / tool_call_traces / api_request_log — old traces
     embed pre-scrub tool outputs (raw email_from etc.).
  5. Verifies: no address-shaped strings remain in any scrubbed column.

Embeddings note: chunks whose text changed are slightly out of sync with their
vectors. Header lines carry little semantic weight, so the drift is accepted
rather than re-embedding (re-run scripts/embed.py on changed rows if needed).

Run from backend/:
    python scripts/scrub_pii.py
"""

import os
import sys
from pathlib import Path

import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent.parent))
from app.utils.redact import make_name_scrubber, scrub_text  # noqa: E402

load_dotenv(Path(__file__).parent.parent.parent / ".env")
DB_URL = os.environ["DATABASE_URL_SYNC"].replace("postgresql+asyncpg://", "postgresql://")

# Known sender/recipient names to remove from prose (signatures, subjects,
# boilerplate). Generated by scripts/build_scrub_literals.py; gitignored.
LITERALS_PATH = Path(__file__).parent.parent / "scrub_literals.txt"
if LITERALS_PATH.exists():
    scrub_names = make_name_scrubber(LITERALS_PATH.read_text().splitlines())
else:
    print(f"WARNING: {LITERALS_PATH.name} not found — name scrub skipped. "
          "Run scripts/build_scrub_literals.py first.", file=sys.stderr)
    scrub_names = lambda t: t  # noqa: E731


def full_scrub(text):
    return scrub_names(scrub_text(text))


# Chunking params — must match scripts/migrate.py
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200


def chunk_text(text: str) -> list[str]:
    if not text or len(text) < 50:
        return []
    chunks, start = [], 0
    while start < len(text):
        end = start + CHUNK_SIZE
        chunks.append(text[start:end])
        if end >= len(text):
            break
        start = end - CHUNK_OVERLAP
    return chunks


def rebuild_chunks(cur):
    """Rebuild email_chunks from the scrubbed email bodies.

    Scrubbing chunks in place cannot work: the 1000/200 chunking splits
    tracking URLs across chunk boundaries, leaving unmatchable fragments.
    Chunks are pure derivatives of emails.email_body, so re-derive them.
    Embeddings are reset to NULL — re-run `python scripts/embed.py --table
    chunks` afterwards.
    """
    import uuid

    # preserve the source_org each email's chunks carried
    cur.execute("""
        SELECT DISTINCT ON (email_content_hash) email_content_hash, source_org
        FROM email_chunks WHERE source_org IS NOT NULL
        ORDER BY email_content_hash, chunk_index
    """)
    org_by_hash = dict(cur.fetchall())

    cur.execute("DELETE FROM email_chunks")
    cur.execute("SELECT email_content_hash, email_subject, email_sent_dt, email_body FROM emails")
    rows = []
    for h, subject, sent_dt, body in cur.fetchall():
        for i, chunk in enumerate(chunk_text(body or "")):
            chunk_id = str(uuid.uuid5(uuid.NAMESPACE_URL, f"{h}:{i}"))
            rows.append((chunk_id, h, i, chunk, sent_dt, subject, org_by_hash.get(h)))
    psycopg2.extras.execute_values(
        cur,
        """INSERT INTO email_chunks
           (chunk_id, email_content_hash, chunk_index, chunk_text,
            email_sent_dt, email_subject, source_org)
           VALUES %s""",
        rows, page_size=500,
    )
    print(f"email_chunks rebuilt from scrubbed bodies: {len(rows):,} chunks "
          "(embeddings reset — run scripts/embed.py --table chunks)")

# \y = Postgres word boundary (\b equivalent). Without it the check prefix-matches
# MIME Content-IDs like image001.png@01DCE219.2F23D710, which are not addresses.
ADDRESS_SQL_RE = r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\y"


def scrub_columns(cur, table: str, pk: str, cols: list[str]) -> list:
    """Scrub text columns in-place; returns the pks of changed rows."""
    cur.execute(f"SELECT {pk}, {', '.join(cols)} FROM {table}")
    rows = cur.fetchall()
    updates, changed = [], []
    for row in rows:
        pk_val, *vals = row
        new_vals = [full_scrub(v) for v in vals]
        if new_vals != vals:
            updates.append((*new_vals, pk_val))
            changed.append(pk_val)
    if updates:
        set_clause = ", ".join(f"{c} = %s" for c in cols)
        psycopg2.extras.execute_batch(
            cur, f"UPDATE {table} SET {set_clause} WHERE {pk} = %s", updates, page_size=500
        )
    print(f"  {table:<20} {len(changed):>7,} of {len(rows):>7,} rows scrubbed "
          f"(cols: {', '.join(cols)})")
    return changed


def main():
    print(f"Connecting to: {DB_URL[:50]}…")
    conn = psycopg2.connect(DB_URL)
    conn.autocommit = False
    cur = conn.cursor()

    try:
        # 1. Structured sender/recipient fields
        cur.execute("""
            UPDATE emails SET email_from = NULL, email_to = NULL
            WHERE email_from IS NOT NULL OR email_to IS NOT NULL
        """)
        print(f"emails.email_from / email_to nulled: {cur.rowcount:,} rows")

        # 2. Free-text scrub
        print("Scrubbing free text…")
        scrub_columns(cur, "emails", "email_content_hash", ["email_subject", "email_body"])
        cur.execute("UPDATE emails SET email_body_length = length(email_body) WHERE email_body IS NOT NULL")

        rebuild_chunks(cur)

        kp_changed = scrub_columns(
            cur, "key_points_full", "key_point_id",
            ["email_subject", "key_point_text", "key_point_citation", "key_point_context"],
        )
        ti_changed = scrub_columns(
            cur, "trade_ideas_full", "trade_idea_id",
            ["email_subject", "trade_idea_text", "trade_idea_citation", "trade_idea_context"],
        )

        # 3. Refresh FTS vectors for changed rows (stale after UPDATE)
        if kp_changed:
            cur.execute("""
                UPDATE key_points_full
                SET kp_fts = to_tsvector('english',
                    coalesce(key_point_text, '') || ' ' ||
                    coalesce(key_point_citation, '') || ' ' ||
                    coalesce(key_point_context, ''))
                WHERE key_point_id = ANY(%s)
            """, (kp_changed,))
            print(f"  kp_fts refreshed for {cur.rowcount:,} rows")
        if ti_changed:
            cur.execute("""
                UPDATE trade_ideas_full
                SET ti_fts = to_tsvector('english',
                    coalesce(trade_idea_text, '') || ' ' ||
                    coalesce(trade_idea_citation, '') || ' ' ||
                    coalesce(trade_idea_context, ''))
                WHERE trade_idea_id = ANY(%s)
            """, (ti_changed,))
            print(f"  ti_fts refreshed for {cur.rowcount:,} rows")

        # 4. Old observability traces embed pre-scrub tool outputs
        for t in ("tool_call_traces", "chat_traces", "api_request_log"):
            cur.execute(f"TRUNCATE {t} CASCADE")
        print("Observability tables truncated (contained pre-scrub tool outputs)")

        conn.commit()

        # 5. Verify — every check must return 0
        print("\nVerification (all must be 0):")
        checks = [
            ("emails.email_from/to not null",
             "SELECT count(*) FROM emails WHERE email_from IS NOT NULL OR email_to IS NOT NULL"),
            ("emails.email_body addresses",
             f"SELECT count(*) FROM emails WHERE email_body ~ '{ADDRESS_SQL_RE}'"),
            ("email_chunks.chunk_text addresses",
             f"SELECT count(*) FROM email_chunks WHERE chunk_text ~ '{ADDRESS_SQL_RE}'"),
            ("key_points_full text addresses",
             f"""SELECT count(*) FROM key_points_full
                 WHERE coalesce(key_point_text,'') || coalesce(key_point_citation,'')
                       || coalesce(key_point_context,'') ~ '{ADDRESS_SQL_RE}'"""),
            ("trade_ideas_full text addresses",
             f"""SELECT count(*) FROM trade_ideas_full
                 WHERE coalesce(trade_idea_text,'') || coalesce(trade_idea_citation,'')
                       || coalesce(trade_idea_context,'') ~ '{ADDRESS_SQL_RE}'"""),
            ("emails.email_body tracking links",
             "SELECT count(*) FROM emails WHERE email_body ~* '<(https?|mailto|tel):'"),
            ("email_chunks tracking links",
             "SELECT count(*) FROM email_chunks WHERE chunk_text ~* '<(https?|mailto|tel):'"),
        ]
        failed = False
        for label, sql in checks:
            cur.execute(sql)
            n = cur.fetchone()[0]
            status = "OK" if n == 0 else "FAIL"
            if n:
                failed = True
            print(f"  [{status}] {label}: {n}")

        # Known-name checks (regex built from the gitignored literals file)
        if LITERALS_PATH.exists():
            import re as _re
            lits = [lit.strip() for lit in LITERALS_PATH.read_text().splitlines() if lit.strip()]
            # "~"-prefixed literals (domain labels) match as substrings; the
            # rest on \y word boundaries — mirrors make_name_scrubber.
            parts = [_re.escape(lit[1:]) for lit in lits if lit.startswith("~")]
            parts += [r"\y" + _re.escape(lit) + r"\y" for lit in lits if not lit.startswith("~")]
            name_re = "|".join(parts)
            name_checks = [
                ("emails subject/body known names",
                 """SELECT count(*) FROM emails
                    WHERE coalesce(email_subject,'') || ' ' || coalesce(email_body,'') ~* %s"""),
                ("email_chunks known names",
                 """SELECT count(*) FROM email_chunks
                    WHERE coalesce(email_subject,'') || ' ' || coalesce(chunk_text,'') ~* %s"""),
                ("key_points_full known names",
                 """SELECT count(*) FROM key_points_full
                    WHERE coalesce(email_subject,'') || coalesce(key_point_text,'')
                          || coalesce(key_point_citation,'') || coalesce(key_point_context,'') ~* %s"""),
                ("trade_ideas_full known names",
                 """SELECT count(*) FROM trade_ideas_full
                    WHERE coalesce(email_subject,'') || coalesce(trade_idea_text,'')
                          || coalesce(trade_idea_citation,'') || coalesce(trade_idea_context,'') ~* %s"""),
            ]
            for label, sql in name_checks:
                cur.execute(sql, (name_re,))
                n = cur.fetchone()[0]
                status = "OK" if n == 0 else "FAIL"
                if n:
                    failed = True
                print(f"  [{status}] {label}: {n}")

        if failed:
            print("\nSCRUB INCOMPLETE — inspect the failing rows above.", file=sys.stderr)
            sys.exit(1)
        print("\nScrub complete — senders/recipients are no longer stored.")

    except Exception as e:
        conn.rollback()
        print(f"\nERROR — rolled back: {e}", file=sys.stderr)
        raise
    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    main()
