"""PII scrubbing helpers shared by API routers and data scripts.

Two layers:
- strip_header_lines: removes forwarded-email header lines (From:/To:/Cc:/...)
  which carry sender/recipient names and addresses.
- redact_addresses: replaces any remaining email addresses with [redacted].

scrub_text() applies both and is the canonical scrub used at ingestion
(scripts/migrate.py) and in the one-time DB scrub (scripts/scrub_pii.py).
Routers apply redact_addresses() alone as defense-in-depth on already-scrubbed
data.
"""

import re

EMAIL_ADDRESS_RE = re.compile(r"\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}\b")

# Angle-bracket link wrappers from plain-text email conversion:
# "Read Full Report <https://url.uk.m.mimecastprotect.com/...>".
# Mimecast/Proofpoint rewrite URLs are per-recipient tracking links — a
# traceability vector, not just clutter — so drop the whole wrapper.
ANGLE_LINK_RE = re.compile(r"<(?:https?|mailto|tel):[^>]*>", re.IGNORECASE)

# International-format phone numbers (contact info in signatures). Requires a
# leading "+" so prices/dates in financial prose are never touched.
PHONE_RE = re.compile(r"\+\d[\d\s().-]{6,}\d")

# Copyright boilerplate lines: "© 2026 Citigroup Inc. No redistribution…".
# Anchored to line start (©/Copyright) so prose mentioning copyright survives.
COPYRIGHT_LINE_RE = re.compile(
    r"^[ \t>]*(?:©|\bcopyright\b\s+(?:©\s*)?\d{4}).*$",
    re.IGNORECASE | re.MULTILINE,
)

# Forwarded-header lines, incl. quoted ones ("> From: ..."). Requires the colon
# directly after the keyword so prose like "From the CIO: ..." is not matched.
HEADER_LINE_RE = re.compile(
    r"^[ \t>]*(from|to|cc|bcc|sent|reply-to)[ \t]*:.*$",
    re.IGNORECASE | re.MULTILINE,
)

REDACTED = "[redacted]"


def redact_addresses(text: str | None) -> str | None:
    if not text:
        return text
    return EMAIL_ADDRESS_RE.sub(REDACTED, text)


def strip_header_lines(text: str | None) -> str | None:
    if not text:
        return text
    return HEADER_LINE_RE.sub("", text)


def strip_links(text: str | None) -> str | None:
    if not text:
        return text
    return ANGLE_LINK_RE.sub("", text)


def strip_copyright_lines(text: str | None) -> str | None:
    if not text:
        return text
    return COPYRIGHT_LINE_RE.sub("", text)


def redact_phones(text: str | None) -> str | None:
    if not text:
        return text
    return PHONE_RE.sub(REDACTED, text)


def scrub_text(text: str | None) -> str | None:
    """Full scrub: tracking links, copyright lines, forwarded headers,
    addresses, phone numbers."""
    return redact_phones(
        redact_addresses(strip_header_lines(strip_copyright_lines(strip_links(text))))
    )


def make_name_scrubber(literals: list[str]):
    """Compile a scrubber for known sender/recipient names in prose.

    literals come from backend/scrub_literals.txt (gitignored; generated by
    scripts/build_scrub_literals.py). Plain lines match case-insensitively on
    word boundaries; lines prefixed "~" match as substrings (domain labels,
    which hide inside URL-encoded addresses and logo filenames). Longer
    literals are tried first so full names win over parts.
    Returns a callable(text) -> text, or an identity fn for an empty list.
    """
    bounded, substr = [], []
    for lit in literals:
        lit = lit.strip()
        if not lit:
            continue
        (substr if lit.startswith("~") else bounded).append(lit.lstrip("~"))
    parts = [re.escape(lit) for lit in sorted(substr, key=len, reverse=True)]
    parts += [
        r"\b" + re.escape(lit) + r"\b"
        for lit in sorted(bounded, key=len, reverse=True)
    ]
    if not parts:
        return lambda text: text
    pattern = re.compile("|".join(parts), re.IGNORECASE)
    return lambda text: pattern.sub(REDACTED, text) if text else text
